### PR TITLE
irc: rate-limit sends to prevent flooding.

### LINKED ISSUE #82: irc: rate-limit sends
IRC breaks messages on lines and does one send for each. Messages with many lines flood and get us kicked.

### PR DESCRIPTION
**Pull request by eaburns**
Fixes #82.

### CODE REVIEW

**Comment by eaburns** [comment]
I'm worried that in the face of flooding, the irc.Channel.Send can block for up to 10s. In the current bridge implementation, this will block relaying all messages during that time.

**Comment by eaburns** [comment]
I think the solution is for the bridge to set a deadline on the send contexts. This way, it'll stop waiting for irc after a couple of seconds, and just abandon it. Basically the send will continue, we just won't wait for the proper error return from it.

Thoughts?

**Comment by chrissexton** [comment]
If we have to block on IRC, then yea it ought to happen out of band of the rest of the work. If IRC errors in such a case, "fuck it"? 

It seems to me that IRC is flaky enough as a protocol that I have no reason to believe I'm going to see messages to begin with, as would be the case in a split. I'd really hate for a split to take down the other networks.

**Review by chrissexton — APPROVED** [review]
Seems like a fine solution, in any case.

**Comment by eaburns** [comment]
Well the problem wouldn't be a split. The issue is rate-limiting it sends. A messages can cause IRC's send to block arbitrarily long: send a message with 100s of newlines; they send in 5 message bursts with a 10s delay between each burst. That would block the bridge for as long as you want.

I'll add a context timeout on bridge sends, so those silly things just get abandoned.

**Comment by eaburns** [comment]
This is in.

**Pull request closed without merging**
