### PR TITLE
chat/irc: add an IRC client.

### PR DESCRIPTION
**Pull request by eaburns**

### CODE REVIEW

**Comment by eaburns** [comment]
FYI, much of the low-level IRC code was copied from github.com/velour/relay, which itself is mostly a cleaned-up version of github.com/velour/velour—the project that started it all.

**Comment by chrissexton** [comment]
Do we need to be doing stuff in this code to support "\x01ACTION"? Telegram doesn't do shit with it, it seems, but both IRC and slack support a /me.

**Comment by eaburns** [comment]
Probably, but I figured we'd get to it after basic messaging. I think we'd need to add both an Emote event type and a Channel.Emote method.

**Comment by chrissexton** [comment]
Cool.

**Pull request merged**
